/**
 * Canonical error-code catalog for the shared error envelope
 * `{ statusCode, code, message, details? }`.
 *
 * Codes are stable strings consumed by the frontend (e.g. NextAuth signIn
 * callback maps `NOT_INVITED` → `/signin?error=not_invited`). Adding a new
 * code is a code change; removing one is a breaking contract change.
 *
 * Grouped by domain for readability — the runtime string is what callers
 * compare against.
 */
export const ErrorCode = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',

  // Auth / session
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INTERNAL_FORBIDDEN: 'AUTH_INTERNAL_FORBIDDEN',

  // Resolve flow
  EMAIL_UNVERIFIED: 'EMAIL_UNVERIFIED',
  NOT_INVITED: 'NOT_INVITED',
  USER_DISABLED: 'USER_DISABLED',

  // Authorization
  INSUFFICIENT_PERMISSION: 'INSUFFICIENT_PERMISSION',
  INSUFFICIENT_PERMISSION_SCOPE: 'INSUFFICIENT_PERMISSION_SCOPE',

  // Schedules (F06)
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  SCHEDULE_OVERLAP: 'SCHEDULE_OVERLAP',
  SCHEDULE_START_IN_PAST: 'SCHEDULE_START_IN_PAST',
  DOCTOR_NOT_IN_DEPARTMENT: 'DOCTOR_NOT_IN_DEPARTMENT',
  DOCTOR_DEPARTMENT_MISMATCH: 'DOCTOR_DEPARTMENT_MISMATCH',

  // Slots (F07)
  DEPARTMENT_TYPE_NOT_ALLOWED: 'DEPARTMENT_TYPE_NOT_ALLOWED',

  // Medical records (F08)
  MEDICAL_RECORD_ALREADY_EXISTS: 'MEDICAL_RECORD_ALREADY_EXISTS',

  // Patients (F09)
  PATIENT_EMAIL_EXISTS: 'PATIENT_EMAIL_EXISTS',

  // Appointments / booking (F09)
  SLOT_TAKEN: 'SLOT_TAKEN',
  SLOT_OUTSIDE_SCHEDULE: 'SLOT_OUTSIDE_SCHEDULE',
  SLOT_OVERLAPS_BREAK: 'SLOT_OVERLAPS_BREAK',
  SLOT_NOT_ON_GRID: 'SLOT_NOT_ON_GRID',
  SCHEDULE_NOT_FOUND_FOR_BOOKING: 'SCHEDULE_NOT_FOUND_FOR_BOOKING',
  SCHEDULE_NOT_BOOKABLE: 'SCHEDULE_NOT_BOOKABLE',
  APPOINTMENT_START_IN_PAST: 'APPOINTMENT_START_IN_PAST',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_ALREADY_CANCELLED: 'APPOINTMENT_ALREADY_CANCELLED',
  APPOINTMENT_ALREADY_COMPLETED: 'APPOINTMENT_ALREADY_COMPLETED',

  // Per-(department, type) booking rules (F13)
  APPOINTMENT_OUTSIDE_BOOKING_WINDOW: 'APPOINTMENT_OUTSIDE_BOOKING_WINDOW',

  // Appointment groups + referrals (F14)
  APPOINTMENT_NOT_BOOKED: 'APPOINTMENT_NOT_BOOKED',
  APPOINTMENT_ALREADY_REFERRED: 'APPOINTMENT_ALREADY_REFERRED',
  APPOINTMENT_GROUP_CLOSED: 'APPOINTMENT_GROUP_CLOSED',
  APPOINTMENT_GROUP_PATIENT_MISMATCH: 'APPOINTMENT_GROUP_PATIENT_MISMATCH',
  APPOINTMENT_GROUP_CLOSE_FORBIDDEN: 'APPOINTMENT_GROUP_CLOSE_FORBIDDEN',
  APPOINTMENT_GROUP_NOT_FOUND: 'APPOINTMENT_GROUP_NOT_FOUND',
  PREVIOUS_APPOINTMENT_NOT_FOUND: 'PREVIOUS_APPOINTMENT_NOT_FOUND',
  PREVIOUS_APPOINTMENT_CANCELLED: 'PREVIOUS_APPOINTMENT_CANCELLED',
  PREVIOUS_APPOINTMENT_NOT_COMPLETED: 'PREVIOUS_APPOINTMENT_NOT_COMPLETED',
  CONTINUATION_APPOINTMENT_TYPE_INVALID: 'CONTINUATION_APPOINTMENT_TYPE_INVALID',
  STANDALONE_APPOINTMENT_TYPE_INVALID: 'STANDALONE_APPOINTMENT_TYPE_INVALID',
  REFERRAL_DEPARTMENT_MISMATCH: 'REFERRAL_DEPARTMENT_MISMATCH',
  REFERRAL_ALREADY_FULFILLED: 'REFERRAL_ALREADY_FULFILLED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * Shape of every non-2xx response body. The global `HttpExceptionFilter`
 * coerces every thrown exception (including class-validator failures) into
 * this envelope.
 */
export interface ErrorEnvelope {
  statusCode: number;
  code: ErrorCodeValue | string;
  message: string;
  details?: Record<string, unknown>;
}
