/* eslint-disable */
// AUTO-GENERATED by scripts/gen-i18n-keys.mjs from src/messages/en.json.
// DO NOT EDIT BY HAND. Run `pnpm --filter @hospital/web gen:i18n` to regenerate.

export const K = {
  Home: {
    primaryAction: "primaryAction",
    secondaryAction: "secondaryAction",
    subtitle: "subtitle",
    title: "title",
  },
  NotFound: {
    description: "description",
    goHome: "goHome",
    title: "title",
  },
} as const;
