/* eslint-disable */
// AUTO-GENERATED by scripts/gen-i18n-keys.mjs from src/messages/en.json.
// DO NOT EDIT BY HAND. Run `pnpm --filter @hospital/web gen:i18n` to regenerate.

export const K = {
  Breadcrumb: {
    admin: "admin",
    departments: "departments",
    doctors: "doctors",
    home: "home",
    me: "me",
    schedule: "schedule",
    staff: "staff",
  },
  Dashboard: {
    comingSoonAdmin: "comingSoonAdmin",
    comingSoonDoctor: "comingSoonDoctor",
    comingSoonStaff: "comingSoonStaff",
    noPermissions: "noPermissions",
    permissionsLabel: "permissionsLabel",
    roleLabel: "roleLabel",
    welcome: "welcome",
  },
  Directory: {
    Departments: {
      doctorsCount: "doctorsCount",
      empty: "empty",
      subtitle: "subtitle",
      title: "title",
    },
    DoctorDetail: {
      back: "back",
      contact: "contact",
      departmentsLabel: "departmentsLabel",
      doctorCode: "doctorCode",
      licenseNo: "licenseNo",
      notFound: "notFound",
      phone: "phone",
      scheduleEmpty: "scheduleEmpty",
      scheduleSummary: "scheduleSummary",
    },
    Doctors: {
      allDepartments: "allDepartments",
      empty: "empty",
      filterByDepartment: "filterByDepartment",
      primary: "primary",
      subtitle: "subtitle",
      title: "title",
      viewDetail: "viewDetail",
    },
    Errors: {
      forbidden: "forbidden",
      loadFailed: "loadFailed",
    },
  },
  Home: {
    primaryAction: "primaryAction",
    secondaryAction: "secondaryAction",
    subtitle: "subtitle",
    title: "title",
  },
  Nav: {
    brand: "brand",
    brandFull: "brandFull",
    closeMenu: "closeMenu",
    collapse: "collapse",
    expand: "expand",
    items: {
      dashboard: "dashboard",
      departments: "departments",
      doctors: "doctors",
      mySchedule: "mySchedule",
    },
    openMenu: "openMenu",
  },
  NotFound: {
    description: "description",
    goHome: "goHome",
    title: "title",
  },
  SignIn: {
    continueWithGoogle: "continueWithGoogle",
    errors: {
      email_unverified: "email_unverified",
      internal: "internal",
      not_invited: "not_invited",
      user_disabled: "user_disabled",
    },
    subtitle: "subtitle",
    title: "title",
  },
  SignOut: {
    label: "label",
  },
  UserMenu: {
    language: "language",
    openMenu: "openMenu",
    signedInAs: "signedInAs",
  },
} as const;

/**
 * Namespace catalog for use with next-intl's `useTranslations(NS.X)` /
 * `getTranslations(NS.X)`. Flat keys are PascalCase-concatenated paths
 * (e.g. `SignIn.errors` → `NS.SignInErrors`).
 */
export const NS = {
  Breadcrumb: "Breadcrumb",
  Dashboard: "Dashboard",
  Directory: "Directory",
  DirectoryDepartments: "Directory.Departments",
  DirectoryDoctorDetail: "Directory.DoctorDetail",
  DirectoryDoctors: "Directory.Doctors",
  DirectoryErrors: "Directory.Errors",
  Home: "Home",
  Nav: "Nav",
  NavItems: "Nav.items",
  NotFound: "NotFound",
  SignIn: "SignIn",
  SignInErrors: "SignIn.errors",
  SignOut: "SignOut",
  UserMenu: "UserMenu",
} as const;
